# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Software Engineering Portfolio - Aemooooon'
tagline:          'Aemooooon portfolio for Software Engineering'
description:      'All of the procedual from Software Engineering that includes evidence, learning log, reflection.'
url:              'https://softenop.github.io/soften-portfolio-aemooooon'
baseurl:          '/soften-portfolio-aemooooon/'

# Navigation
navigation:
- text: Sprint Golas
  url: /soften-portfolio-aemooooon/sprintgoals/
- text: Agile
  url: /soften-portfolio-aemooooon/agile/
- text: Reflection
  url: /soften-portfolio-aemooooon/reflection/
#- text: Team Member
#  url: /soften-portfolio-aemooooon/team/
# - text: Blog
#   url: /soften-portfolio-aemooooon/blog/
# - text: Tags
#   url: /soften-portfolio-aemooooon/tags/
# - text: Archive
#   url : /soften-portfolio-aemooooon/archive/
# - text: Search
#   url: /soften-portfolio-aemooooon/search/


# Author Details
author:         'Hua WANG'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/hua.wang.71'
flickr:
github:         'https://github.com/aemooooon'
#gplus:          'https://plus.google.com/100425464897246255887/'
instagram:      'https://www.instagram.com/aemooooon/'
pinterest:
linkedin:   
rss:
#stackoverflow:  'http://stackoverflow.com/users/185655/abdel-raoof'
#twitter:        'https://twitter.com/olakara'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
